name: "Download and Cache Shared Data"
description: "Composite action to restore, download, and cache shared data"

inputs:
  os:
    description: "Runner OS (for cache key). Defaults to runner.os if not set"
    required: false
    default: "${{ runner.os }}"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore shared data cache
      id: cache-data
      uses: actions/cache@v4
      with:
        path: data/
        key: "${{ inputs.os }}-${{ hashFiles('.github/scripts/download_data.py') }}"
        restore-keys: |
          "${{ inputs.os }}-"

    - name: Download data if cache missed
      if: steps.cache-data.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Cache miss, downloading data..."
        python .github/scripts/download_data.py
