"""Next Generation file format IO."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("ngio")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "uninstalled"
__author__ = "Lorenzo Cerrone"
__email__ = "lorenzo.cerrone@uzh.ch"

from ngio.common import Dimensions, Roi, RoiSlice
from ngio.config import (
    ConsolidationConfig,
    DaskConfig,
    NgioConfig,
    RetryConfig,
    S3FSConfig,
    ZarrConfig,
    get_config,
)
from ngio.hcs import (
    OmeZarrPlate,
    OmeZarrWell,
    create_empty_plate,
    create_empty_well,
    derive_ome_zarr_plate,
    open_ome_zarr_plate,
    open_ome_zarr_well,
)
from ngio.images import (
    ChannelSelectionModel,
    Image,
    Label,
    MaskedImage,
    MaskedLabel,
    OmeZarrContainer,
    create_empty_ome_zarr,
    create_ome_zarr_from_array,
    create_synthetic_ome_zarr,
    open_image,
    open_label,
    open_ome_zarr_container,
)
from ngio.iterators import (
    AbstractIteratorBuilder,
    BasicMapper,
    BatchedMapper,
    FeatureExtractorIterator,
    FeatureFuncResult,
    HaloMargins,
    ImageProcessingIterator,
    IterUnit,
    JobArgs,
    MapperProtocol,
    MaskedSegmentationIterator,
    MaxWorkers,
    NmsConfig,
    ObjectDetectionIterator,
    ProcessMapper,
    SegmentationIterator,
    StitchConfig,
    TailPolicy,
    ThreadedMapper,
    canonical_unit_order,
    compute_write_footprint,
    plan_waves,
    write_conflict_components,
)
from ngio.ome_zarr_meta import (
    get_ngio_image_meta,
    get_ngio_label_meta,
    get_ngio_labels_group_meta,
    get_ngio_meta,
    get_ngio_plate_meta,
    get_ngio_well_meta,
)
from ngio.ome_zarr_meta.ngio_specs import (
    AxesSetup,
    Channel,
    DefaultNgffVersion,
    ImageInWellPath,
    NgffVersions,
    PixelSize,
)
from ngio.resources import get_sample_info
from ngio.utils import (
    NgioError,
    NgioFileExistsError,
    NgioFileNotFoundError,
    NgioKeyError,
    NgioSupportedStore,
    NgioTableValidationError,
    NgioValidationError,
    NgioValueError,
    StoreOrGroup,
)

__all__ = [
    "AbstractIteratorBuilder",
    "AxesSetup",
    "BasicMapper",
    "BatchedMapper",
    "Channel",
    "ChannelSelectionModel",
    "ConsolidationConfig",
    "DaskConfig",
    "DefaultNgffVersion",
    "Dimensions",
    "FeatureExtractorIterator",
    "FeatureFuncResult",
    "HaloMargins",
    "Image",
    "ImageInWellPath",
    "ImageProcessingIterator",
    "IterUnit",
    "JobArgs",
    "Label",
    "MapperProtocol",
    "MaskedImage",
    "MaskedLabel",
    "MaskedSegmentationIterator",
    "MaxWorkers",
    "NgffVersions",
    "NgioConfig",
    "NgioError",
    "NgioFileExistsError",
    "NgioFileNotFoundError",
    "NgioKeyError",
    "NgioSupportedStore",
    "NgioTableValidationError",
    "NgioValidationError",
    "NgioValueError",
    "NmsConfig",
    "ObjectDetectionIterator",
    "OmeZarrContainer",
    "OmeZarrPlate",
    "OmeZarrWell",
    "PixelSize",
    "ProcessMapper",
    "RetryConfig",
    "Roi",
    "RoiSlice",
    "S3FSConfig",
    "SegmentationIterator",
    "StitchConfig",
    "StoreOrGroup",
    "TailPolicy",
    "ThreadedMapper",
    "ZarrConfig",
    "__version__",
    "canonical_unit_order",
    "compute_write_footprint",
    "create_empty_ome_zarr",
    "create_empty_plate",
    "create_empty_well",
    "create_ome_zarr_from_array",
    "create_synthetic_ome_zarr",
    "derive_ome_zarr_plate",
    "get_config",
    "get_ngio_image_meta",
    "get_ngio_label_meta",
    "get_ngio_labels_group_meta",
    "get_ngio_meta",
    "get_ngio_plate_meta",
    "get_ngio_well_meta",
    "get_sample_info",
    "open_image",
    "open_label",
    "open_ome_zarr_container",
    "open_ome_zarr_plate",
    "open_ome_zarr_well",
    "plan_waves",
    "write_conflict_components",
]
