name: Build Docs

on:
  push:
    branches:
      - main
      - docs_update
    tags:
      - "v*"

jobs:
  download-test-ome-zarr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check and Download Artifacts
        run: |
          bash .github/scripts/download_data.sh

  deploy:
    name: Deploy Docs
    needs: download-test-ome-zarr
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache-dependency-path: "pyproject.toml"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .[dev]
          python -m pip install .[docs]

      - name: Configure Git for Mike
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Deploy Docs with Mike
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            mike deploy latest --push --update-aliases
          elif [[ "${GITHUB_REF}" == "refs/heads/docs_update" ]]; then
            mike deploy dev --push --update-aliases
          else
            VERSION=${GITHUB_REF#refs/tags/v}
            mike deploy "$VERSION" --push --update-aliases
            mike set-default "$VERSION" --push
          fi

      # If something goes wrong with --pre tests, we can open an issue in the repo
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site